{-# OPTIONS --without-K #-}

-- `Hypothesis` (cxm-plan.md Phase 7, §4.7) — an inference with confidence, evidence and status,
-- in the Knowledge envelope (type HYPOTHESIS, source INFERRED, confidence < 1000). [ПР]:
-- generated by inference and moved along confidence / into REFUTED, never deleted (§4.1, §4.16).
-- The revision operators live in Cxm.Inference; this module is the constructor.
module Cxm.Hypothesis where

open import Data.Nat using (ℕ; _<?_)
open import Data.Maybe using (nothing)
open import Data.String using (String)
open import Relation.Nullary.Decidable using (True)

open import Cxm.Num using (Permille; permilleMax)
open import Cxm.Tenant using (TenantId)
open import Cxm.Knowledge

-- a fresh open-ended HYPOTHESIS; `conf < 1000` is proof-gated (auto-solved for literals);
-- kId 0 = assigned on insert; evidence is attached separately (Evidence child table).
hypothesize : (subject : ℕ) (tenant : TenantId) (conf : Permille) {pf : True (conf <? permilleMax)}
              (claim : String) (decay validFrom : ℕ) → Knowledge
hypothesize subj ten conf {pf} claim dec vf = mkInferred 0 subj ten IHypothesis conf {pf} claim dec vf nothing nothing
